// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class __EFMigrationsHistory
{
    public string MigrationId { get; set; }
    public string ProductVersion { get; set; }
}
