// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class AccountYearEndClosing
{
    public decimal? Account_Sn { get; set; }
    public decimal? Account_No { get; set; }
    public string Account_Name { get; set; }
    public decimal? Credit { get; set; }
    public decimal? Debit { get; set; }
    public decimal? ViewBalance { get; set; }
    public bool? IsUpdate { get; set; }
}
