// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Account_Branch
{
    public int ID { get; set; }
    public string Name { get; set; }
    public int? AccountNo { get; set; }
    public string Phone { get; set; }
    public string Fax { get; set; }
    public string Address { get; set; }
    public string Note { get; set; }
    public int? UserID_Add { get; set; }
    public int? UserBranch_Add { get; set; }
    public string UserMacAddress_Add { get; set; }
    public DateTime? UserDate_Add { get; set; }
    public int? UserID_Update { get; set; }
    public int? UserBranch_Update { get; set; }
    public string UserMacAddress_Update { get; set; }
    public DateTime? UserDate_Update { get; set; }
}
