// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Account_CustSup
{
    public int ID { get; set; }
    public int? CustSuppCode { get; set; }
    public int? AccountNo { get; set; }
    public int? BranchID { get; set; }
    public string CustSuppName { get; set; }
    public string VatNum { get; set; }
    public string Phone { get; set; }
    public string Fax { get; set; }
    public string Address { get; set; }
    public int? PlaceID { get; set; }
    public int? SalesManID { get; set; }
    public decimal? CreditLimit { get; set; }
    public decimal? AlarmLimit { get; set; }
    public bool? IsSuppliers { get; set; }
    public bool? IsCustomers { get; set; }
    public bool? FrmCust { get; set; }
    public string Note { get; set; }
    public int? UserID_Add { get; set; }
    public int? UserBranch_Add { get; set; }
    public string UserMacAddress_Add { get; set; }
    public DateTime? UserDate_Add { get; set; }
    public int? UserID_Update { get; set; }
    public int? UserBranch_Update { get; set; }
    public string UserMacAddress_Update { get; set; }
    public DateTime? UserDate_Update { get; set; }
    public string BuildingNum { get; set; }
    public string Street { get; set; }
    public string District { get; set; }
    public string City { get; set; }
    public string Country { get; set; }
    public string PostalCode { get; set; }
    public string AdditionalNum { get; set; }
    public string CommercialRecord { get; set; }
    public int? FranchiseID { get; set; }
}
