// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Account_Suspended
{
    public int ID { get; set; }
    public string Name { get; set; }
}
