// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Account_DefualtCustomer
{
    public int SN { get; set; }
    public int? ID { get; set; }
    public string Name { get; set; }
    public int? AccountID { get; set; }
    public int? BranchID { get; set; }
}
