// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Account_DefualtAccount
{
    public int ID { get; set; }
    public int? BranchID { get; set; }
    public int? Acc_StoreMain { get; set; }
    public int? Acc_StoreWaiting { get; set; }
    public int? Acc_CostItemOrder { get; set; }
    public int? Acc_VatNum { get; set; }
    public int? Acc_CashBox { get; set; }
    public int? Acc_OrderCash { get; set; }
    public int? Acc_OrderAjila { get; set; }
    public int? Acc_OrderReturnCash { get; set; }
    public int? Acc_BankNumCachir { get; set; }
    public int? Acc_CustomerCash { get; set; }
    public int? Acc_supplierCash { get; set; }
    public int? StoreEntagTam { get; set; }
    public int? StoreMawadAwalyaa { get; set; }
}
