// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class AccountStartBalance
{
    public int Id { get; set; }
    public decimal? AccountNo { get; set; }
    public decimal? Priv_Debit { get; set; }
    public decimal? Priv_Credit { get; set; }
    public int CompID { get; set; }
    public DateTime? StartDate { get; set; }
    public int? CreatedBy { get; set; }
    public bool? AllowEdit { get; set; }
}
