// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Account_CostCenters
{
    public int SN { get; set; }
    public int? CostCentersID { get; set; }
    public int? CostCentersNo { get; set; }
    public string CostCentersName { get; set; }
    public int? MainCostCentersID { get; set; }
    public decimal? Priv_Credit { get; set; }
    public decimal? Priv_Debit { get; set; }
    public string Note { get; set; }
    public int? BranchID { get; set; }
    public int? UserID_Add { get; set; }
    public int? UserBranch_Add { get; set; }
    public string UserMacAddress_Add { get; set; }
    public DateTime? UserDate_Add { get; set; }
    public int? UserID_Update { get; set; }
    public int? UserBranch_Update { get; set; }
    public string UserMacAddress_Update { get; set; }
    public DateTime? UserDate_Update { get; set; }
    public bool? HideCost { get; set; }
    public bool? IsDefaulte { get; set; }
}
