// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Account_Accounts
{
    public int ID { get; set; }
    public int? Account_No { get; set; }
    public int? Suspended { get; set; }
    public int? Account_Level { get; set; }
    public int? Final_Account { get; set; }
    public int? Account_Type { get; set; }
    public int? Account_Nature { get; set; }
    public int? Main_Account_No { get; set; }
    public int? BranchID { get; set; }
    public string Account_Name { get; set; }
    public string E_Account_Name { get; set; }
    public decimal? Priv_Debit { get; set; }
    public decimal? Priv_Credit { get; set; }
    public string AddressA { get; set; }
    public string PhoneA { get; set; }
    public string FaxA { get; set; }
    public string Note { get; set; }
    public int? UserID_Add { get; set; }
    public int? UserBranch_Add { get; set; }
    public string UserMacAddress_Add { get; set; }
    public DateTime? UserDate_Add { get; set; }
    public int? UserID_Update { get; set; }
    public int? UserBranch_Update { get; set; }
    public string UserMacAddress_Update { get; set; }
    public DateTime? UserDate_Update { get; set; }
    public DateTime? Date_OpenCharge { get; set; }
}
