// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Account_ProjectsDetails
{
    public int SN { get; set; }
    public int? ProjectAccountID { get; set; }
    public int? CostCenterID { get; set; }
}
