// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Account_CustTailor
{
    public int SN { get; set; }
    public int? CustCode { get; set; }
    public string CollarH { get; set; }
    public string CollarW { get; set; }
    public string ShoulderH { get; set; }
    public string ShoulderW { get; set; }
    public string ChestH { get; set; }
    public string ChestW { get; set; }
    public string WaistH { get; set; }
    public string WaistW { get; set; }
    public string HipsH { get; set; }
    public string HipsW { get; set; }
    public string SleeveH { get; set; }
    public string SleeveW { get; set; }
    public string CuffH { get; set; }
    public string CuffW { get; set; }
    public string LongthH { get; set; }
    public string LongthW { get; set; }
    public string DownDressH { get; set; }
    public string DownDressW { get; set; }
    public string starlings { get; set; }
    public string chestpocket { get; set; }
    public string QuantumPlain { get; set; }
    public string QuantumCuff { get; set; }
    public string ButtonNumber { get; set; }
    public string Note { get; set; }
}
