// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Account_Projects
{
    public int SN { get; set; }
    public int? ProjectID { get; set; }
    public int? ProjectNo { get; set; }
    public string ProjectName { get; set; }
    public DateTime? DateStart { get; set; }
    public DateTime? DateEnd { get; set; }
    public decimal? ProjectPrice { get; set; }
    public decimal? ProjectVat { get; set; }
    public decimal? InsuranceAmount { get; set; }
    public decimal? InsurancePer { get; set; }
    public decimal? TotalAmount { get; set; }
    public string Note { get; set; }
    public int? BranchID { get; set; }
    public int? UserID_Add { get; set; }
    public int? UserBranch_Add { get; set; }
    public string UserMacAddress_Add { get; set; }
    public DateTime? UserDate_Add { get; set; }
    public int? UserID_Update { get; set; }
    public int? UserBranch_Update { get; set; }
    public string UserMacAddress_Update { get; set; }
    public DateTime? UserDate_Update { get; set; }
}
