// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class AccountYears
{
    public int Id { get; set; }
    public string Name { get; set; }
}
