// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class AgeingAnalysis
{
    public decimal AgeingAnalysisID { get; set; }
    public decimal? Account_No { get; set; }
    public string Account_Name { get; set; }
    public decimal? SumValues { get; set; }
    public decimal? Days_30 { get; set; }
    public decimal? Days_31_60 { get; set; }
    public decimal? Days_61_90 { get; set; }
    public decimal? Days_91_180 { get; set; }
    public decimal? Days_180 { get; set; }
    public int? CompID { get; set; }
    public int? EmpID { get; set; }
}
