// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class App_FiscalYearState
{
    public int ID { get; set; }
    public int YearId { get; set; }
    public bool IsOpen { get; set; }
    public DateTime OpenedAt { get; set; }
    public DateTime? ClosedAt { get; set; }
    public string UserName { get; set; }
}
