// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Car_Receive
{
    public int ID { get; set; }
    public int? CustID { get; set; }
    public int? Cust_Fin_Num { get; set; }
    public int? Order_TypeID { get; set; }
    public string Order_Date { get; set; }
    public string Order_DateReceipt { get; set; }
    public string Order_DateResend { get; set; }
    public string Order_Uploader { get; set; }
    public string Order_Destination { get; set; }
    public string Car_bodynumber { get; set; }
    public string Car_TypeID { get; set; }
    public string Car_ColorID { get; set; }
    public string Car_Model { get; set; }
    public string Car_PlateNumber { get; set; }
    public int? DriverID { get; set; }
    public string Driver_PlateNumber { get; set; }
    public decimal? ShippingAmount { get; set; }
    public decimal? DiscountAmount { get; set; }
    public decimal? TotalAmount { get; set; }
    public decimal? VatAmount { get; set; }
    public decimal? SafyAmount { get; set; }
    public decimal? CashAmount { get; set; }
    public decimal? LastCashAmount { get; set; }
    public bool? IsDone { get; set; }
    public string Note { get; set; }
}
