// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Contract_Store
{
    public int ID { get; set; }
    public int? CustID { get; set; }
    public int? ItemID { get; set; }
    public DateTime? ItemDate { get; set; }
    public decimal? Quantity { get; set; }
    public DateTime? ItemDateExpire { get; set; }
    public decimal? QuantityExpire { get; set; }
}
