// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Contract_Bounce
{
    public int SN { get; set; }
    public int? ID { get; set; }
    public string Name { get; set; }
    public int? BranchID { get; set; }
    public decimal? profit { get; set; }
    public bool? ISProfitOrder { get; set; }
    public string Phone { get; set; }
    public int? PlaceID { get; set; }
    public int? UserID_Add { get; set; }
    public int? UserBranch_Add { get; set; }
    public string UserMacAddress_Add { get; set; }
    public DateTime? UserDate_Add { get; set; }
    public int? UserID_Update { get; set; }
    public int? UserBranch_Update { get; set; }
    public string UserMacAddress_Update { get; set; }
    public DateTime? UserDate_Update { get; set; }
    public string PlateNumber { get; set; }
}
