// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Contract_Files
{
    public int ID { get; set; }
    public int ContractID { get; set; }
    public string FilePath { get; set; }
    public DateTime? UploadDate { get; set; }
}
