// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Contract_EJAR
{
    public int ID { get; set; }
    public string ContractRegistryNumber { get; set; }
    public DateTime? TheDateOfTheContract { get; set; }
    public DateTime? TheStartDateOftheLeaseTerm { get; set; }
    public string conditionallySuspended { get; set; }
    public string MethodOfPaymentOfContractFees { get; set; }
    public string TypeOfContract { get; set; }
    public string ThePlaceOfConclusionOfTheContract { get; set; }
    public DateTime? TheEndDateOfTheLeaseTerm { get; set; }
    public string LessorsName { get; set; }
    public string ThelessorsNationality { get; set; }
    public string LessorIDType { get; set; }
    public string ThelandlordsMobileNumber { get; set; }
    public string LandlordNationalAddress { get; set; }
    public string LessorIdentificationNumber { get; set; }
    public string LandlordsEmail { get; set; }
    public string TheLessorIsRepresentedByHimselfOrHerself { get; set; }
    public string TenantAreaType { get; set; }
    public string CommercialRegistrationNumberOfTheTenant { get; set; }
    public string TheIssuingEntityOfTheTenant { get; set; }
    public string TheNameOfTheTenantCompany { get; set; }
    public string UnifiedNumberOfTheTenant { get; set; }
    public string TheDateOfTheCommercialRegistrationOfTheTenant { get; set; }
    public string TheNameOfTheTenantsRepresentative { get; set; }
    public string TheNationalityOfTheTenantsRepresentative { get; set; }
    public string Note { get; set; }
}
