// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class EmployeeAllowances
{
    public int EmployeeID { get; set; }
    public int AllowanceID { get; set; }
    public decimal Money { get; set; }
}
