// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Item_Type
{
    public int SN { get; set; }
    public string TypeName { get; set; }
}
