// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Item_Add
{
    public int ID { get; set; }
    public string Name { get; set; }
    public string NameEN { get; set; }
    public decimal? SellPrice { get; set; }
    public decimal? CostPrice { get; set; }
    public bool? Is_Tax { get; set; }
    public decimal? Tax_Value { get; set; }
    public int? PrintID { get; set; }
    public bool? Type { get; set; }
}
