// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class ItemQuantity
{
    public int ItemQuantityID { get; set; }
    public int? ItemID { get; set; }
    public int? StoreID { get; set; }
    public decimal? OpeningBalance { get; set; }
    public decimal? CurrentBalance { get; set; }
    public decimal? BeginningInventory { get; set; }
    public decimal? BeginningInventoryPrice { get; set; }
    public decimal? UnitNumber { get; set; }
}
