// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class LoginLogs
{
    public int SN { get; set; }
    public int UserID { get; set; }
    public DateTime UserLogsDate { get; set; }
    public string MacAddressLogs { get; set; }
    public string AppVersion { get; set; }
    public string DatabaseVersion { get; set; }
}
