// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Order_PriceOffer
{
    public int ID { get; set; }
    public int? PurBranchID { get; set; }
    public int? BranchID { get; set; }
    public int? SupplierID { get; set; }
    public string SupplierName { get; set; }
    public string SupplierPhone { get; set; }
    public string SupplierVatNum { get; set; }
    public DateTime? Purchases_Date { get; set; }
    public int? Sectoral { get; set; }
    public int? CostCentersID { get; set; }
    public string NoteBig { get; set; }
    public string Note { get; set; }
    public string NoteNum { get; set; }
    public decimal? Tax { get; set; }
    public decimal? TotalPrices { get; set; }
    public decimal? Safy { get; set; }
    public decimal? DiscountNum { get; set; }
    public decimal? DiscountPerantage { get; set; }
    public decimal? Tax_Discount { get; set; }
    public decimal? AllDiscount { get; set; }
    public decimal? TobaccoTax { get; set; }
    public decimal? AllTax { get; set; }
    public decimal? Net { get; set; }
    public int? UserID_Add { get; set; }
    public int? UserBranch_Add { get; set; }
    public string UserMacAddress_Add { get; set; }
    public DateTime? UserDate_Add { get; set; }
    public int? UserID_Update { get; set; }
    public int? UserBranch_Update { get; set; }
    public string UserMacAddress_Update { get; set; }
    public DateTime? UserDate_Update { get; set; }
    public int? ProjectId { get; set; }
    public int? YearId { get; set; }
    public string BuildingNum { get; set; }
    public string Street { get; set; }
    public string District { get; set; }
    public string City { get; set; }
    public string Country { get; set; }
    public string PostalCode { get; set; }
    public string AdditionalNum { get; set; }
    public string CommercialRecord { get; set; }
    public string SalesMan { get; set; }
    public DateTime? DateHold { get; set; }
    public decimal? Charge { get; set; }
    public int? OrderType { get; set; }
}
