// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Order_Reservation
{
    public int ID { get; set; }
    public int? CustID { get; set; }
    public DateTime? DateReserv { get; set; }
    public bool? IsRent { get; set; }
    public DateTime? Rehearsaldate { get; set; }
    public DateTime? Receiveddate { get; set; }
    public DateTime? Eventdate { get; set; }
    public DateTime? Returndate { get; set; }
    public decimal? Net { get; set; }
    public string Note { get; set; }
}
