// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Order_MoveHall
{
    public int Id { get; set; }
    public int? OrderId { get; set; }
    public string NumberOfMen { get; set; }
    public string TheNumberOfMenslengths { get; set; }
    public string TheNumberOfCarcasses { get; set; }
    public string CookingCarcassesOnItsBottom { get; set; }
    public string CarcassType { get; set; }
    public decimal? ThePriceOfTheSacrifice { get; set; }
    public string Trombeh { get; set; }
    public string Bff { get; set; }
    public string NumberOfWomen { get; set; }
    public string TheNumberOfWomensTables { get; set; }
    public string NumberOfWomensCandlesticks { get; set; }
    public string NumberOfHeaters { get; set; }
    public string Kosha { get; set; }
    public string TurnOnHeadphones { get; set; }
    public string AddAwedding { get; set; }
    public string AddCurains { get; set; }
    public string NescafeAndCappuccino { get; set; }
    public string LaserDevices { get; set; }
    public string AddADisplay { get; set; }
    public string TheAdditionOfMensRapture { get; set; }
    public string AnotherGroom { get; set; }
}
