// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class OrderDalala_Sending
{
    public int ID { get; set; }
    public int? PurBranchID { get; set; }
    public int? BranchID { get; set; }
    public int? SupplierID { get; set; }
    public string SupplierName { get; set; }
    public string DriverName { get; set; }
    public string DriverPhone { get; set; }
    public string CarNum { get; set; }
    public string City { get; set; }
    public DateTime? Purchases_Date { get; set; }
    public int? UserID_Add { get; set; }
    public int? UserBranch_Add { get; set; }
    public string UserMacAddress_Add { get; set; }
    public DateTime? UserDate_Add { get; set; }
    public int? UserID_Update { get; set; }
    public int? UserBranch_Update { get; set; }
    public string UserMacAddress_Update { get; set; }
    public DateTime? UserDate_Update { get; set; }
}
