// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class OrderDalala_Dalala
{
    public int ID { get; set; }
    public int? PurBranchID { get; set; }
    public int? FromSendingID { get; set; }
    public int? BranchID { get; set; }
    public int? TypeID { get; set; }
    public int? CustID { get; set; }
    public string CustName { get; set; }
    public int? SupplierID { get; set; }
    public string SupplierName { get; set; }
    public string DriverName { get; set; }
    public string DriverPhone { get; set; }
    public string CarNum { get; set; }
    public string City { get; set; }
    public DateTime? Purchases_Date { get; set; }
    public int? Order_Paymant_Type { get; set; }
    public int? CostCentersID { get; set; }
    public decimal? BouncePerc { get; set; }
    public decimal? Bounce { get; set; }
    public string ExpensesText { get; set; }
    public decimal? Expenses { get; set; }
    public decimal? Employee { get; set; }
    public decimal? CareRent { get; set; }
    public decimal? Market { get; set; }
    public decimal? CostAverg { get; set; }
    public decimal? Tax { get; set; }
    public decimal? TotalPrices { get; set; }
    public decimal? Safy { get; set; }
    public decimal? DiscountNum { get; set; }
    public decimal? DiscountPerantage { get; set; }
    public decimal? Tax_Discount { get; set; }
    public decimal? TotalPrices_Discount { get; set; }
    public decimal? TobaccoTax { get; set; }
    public decimal? AllTax { get; set; }
    public decimal? Net { get; set; }
    public int? UserID_Add { get; set; }
    public int? UserBranch_Add { get; set; }
    public string UserMacAddress_Add { get; set; }
    public DateTime? UserDate_Add { get; set; }
    public int? UserID_Update { get; set; }
    public int? UserBranch_Update { get; set; }
    public string UserMacAddress_Update { get; set; }
    public DateTime? UserDate_Update { get; set; }
    public int? ProjectId { get; set; }
    public int? YearId { get; set; }
}
