// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Order_Extension
{
    public int OrderID { get; set; }
    public string RightSph { get; set; }
    public string RightCYL { get; set; }
    public string RightAxis { get; set; }
    public string RightAdd { get; set; }
    public string LeftSph { get; set; }
    public string LeftCYL { get; set; }
    public string LeftAxis { get; set; }
    public string LeftAdd { get; set; }
    public string Note { get; set; }
}
