// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Order_GardDetails
{
    public int SN { get; set; }
    public int? GardID { get; set; }
    public int? ItemID { get; set; }
    public int? StoreID { get; set; }
    public int? ItemUnitID { get; set; }
    public decimal? SellPrice { get; set; }
    public decimal? LastPrice { get; set; }
    public decimal? AvergPrice { get; set; }
    public decimal? QuantityApp { get; set; }
    public decimal? QuantityGard { get; set; }
    public decimal? QuantitiesDifference { get; set; }
}
