// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Order_OrderReturnDetails
{
    public int SN { get; set; }
    public int? FromPurchID { get; set; }
    public int? Purchese_ID { get; set; }
    public int? CreditNote { get; set; }
    public int? ItemID { get; set; }
    public bool? IsWaiting { get; set; }
    public int? BranchID { get; set; }
    public int? StoreID { get; set; }
    public int? ItemUnitID { get; set; }
    public decimal? Quantity { get; set; }
    public decimal? CostAverg { get; set; }
    public decimal? SmallUnitPrice { get; set; }
    public decimal? UnitPrice { get; set; }
    public decimal? TotalPrice { get; set; }
    public decimal? VAT { get; set; }
    public decimal? NetUnitPrice { get; set; }
    public decimal? NetTotalPrice { get; set; }
    public decimal? VAT_Discount { get; set; }
    public string ItemUnitType { get; set; }
    public decimal? UnitNumber { get; set; }
    public string ItemNote { get; set; }
    public decimal? SumPriceInstall { get; set; }
    public decimal? SumPriceInstallDisc { get; set; }
    public decimal? Originalquantity { get; set; }
    public decimal? AmountDisc { get; set; }
    public decimal? PercentDisc { get; set; }
    public int? SnOrderDetails { get; set; }
}
