// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Order_StoreTransferDetails
{
    public int SN { get; set; }
    public int? Trans_ID { get; set; }
    public int? BranchID { get; set; }
    public int? ItemID { get; set; }
    public int? ItemUnitID { get; set; }
    public decimal? Quantity { get; set; }
    public decimal? SmallUnitPrice { get; set; }
    public decimal? UnitPrice { get; set; }
    public decimal? TotalPrice { get; set; }
    public string ItemUnitType { get; set; }
}
