// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class PriceOffer_Reservations
{
    public int ID { get; set; }
    public int? PriceOfferID { get; set; }
    public int? HallsID { get; set; }
    public DateTime? BookingDate { get; set; }
    public DateTime? InstallationDate { get; set; }
    public DateTime? jawDate { get; set; }
    public int? BranchID { get; set; }
    public int? UserID_Add { get; set; }
    public int? UserBranch_Add { get; set; }
    public string UserMacAddress_Add { get; set; }
    public DateTime? UserDate_Add { get; set; }
    public int? UserID_Update { get; set; }
    public int? UserBranch_Update { get; set; }
    public string UserMacAddress_Update { get; set; }
    public DateTime? UserDate_Update { get; set; }
}
