// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class PrintersCook
{
    public int ID { get; set; }
    public int? PrinterID { get; set; }
    public int? ItemID { get; set; }
    public int? BranchID { get; set; }
}
