// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Printers
{
    public int ID { get; set; }
    public string Name { get; set; }
    public int? BranchID { get; set; }
    public string IPAddress { get; set; }
    public string PortNum { get; set; }
}
