// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class RebuildAllIndexes
{
    public int SN { get; set; }
    public DateTime? RunDate { get; set; }
}
