// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class RentalExpensesDetails
{
    public int SN { get; set; }
    public int? ExpensesId { get; set; }
    public int? ItemId { get; set; }
    public string ItemCode { get; set; }
    public string ItemName { get; set; }
    public string Note { get; set; }
    public decimal? Total { get; set; }
    public decimal? Vat { get; set; }
    public bool? IsVat { get; set; }
    public decimal? Net { get; set; }
}
