// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Restaurant_Delivery
{
    public int SN { get; set; }
    public int? DeliveryID { get; set; }
    public string CustName { get; set; }
    public string CustPhone { get; set; }
    public string CustPlace { get; set; }
    public decimal? Money { get; set; }
    public int? OrderID { get; set; }
    public int? BranchID { get; set; }
}
