// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class ResultElectronicInvoiceXmls
{
    public int Id { get; set; }
    public string OrderId { get; set; }
    public int BranchId { get; set; }
    public bool IsValid { get; set; }
    public string EncodedInvoice { get; set; }
    public string InvoiceHash { get; set; }
    public string UUID { get; set; }
    public string QRCode { get; set; }
    public string SingedXMLFileNameFullPath { get; set; }
    public string AllowanceTotalAmount { get; set; }
    public string ChargeTotalAmount { get; set; }
    public string LineExtensionAmount { get; set; }
    public string TaxExclusiveAmount { get; set; }
    public string TaxInclusiveAmount { get; set; }
    public string PayableAmount { get; set; }
    public string TaxAmount { get; set; }
    public bool? Uploaded { get; set; }
    public DateTime? Created { get; set; }
    public DateTime? UploadedDate { get; set; }
    public string Operation { get; set; }
    public string ErrorMessage { get; set; }
    public string ResultedValue { get; set; }
    public string SingedXML { get; set; }
    public string SingedXMLFileName { get; set; }
    public string PIH { get; set; }
    public string PrepaidAmount { get; set; }
    public string SingedXMLFileNameShortPath { get; set; }
    public string NormalXMLFileNameFullPath { get; set; }
    public string NormalXMLFileNameShortPath { get; set; }
    public string InvoiceTypeName { get; set; }
    public string FatoraType { get; set; }
}
