// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Scaffold_PriceOfferDetails
{
    public int SN { get; set; }
    public int? Purchese_ID { get; set; }
    public int? ItemID { get; set; }
    public int? BranchID { get; set; }
    public int? ItemUnitID { get; set; }
    public decimal? Quantity { get; set; }
    public decimal? LastCost { get; set; }
    public decimal? SmallUnitPrice { get; set; }
    public decimal? UnitPrice { get; set; }
    public decimal? TotalPrice { get; set; }
    public decimal? VAT { get; set; }
    public decimal? NetUnitPrice { get; set; }
    public decimal? NetTotalPrice { get; set; }
    public decimal? VAT_Discount { get; set; }
    public string ItemUnitType { get; set; }
    public DateTime? ItemDate { get; set; }
    public decimal? LastPrice { get; set; }
    public string Statement { get; set; }
}
