// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Tafqit
{
    public int Tafqit_ID { get; set; }
    public string Tafqit_Name { get; set; }
}
