// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class TblRemember
{
    public int ID { get; set; }
    public DateTime? DateTimeRem { get; set; }
    public string NameRem { get; set; }
}
