// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class TempAgeingAnalysis
{
    public decimal? Account_No { get; set; }
    public string Account_Name { get; set; }
    public DateTime? TranDate { get; set; }
    public decimal? Debit { get; set; }
    public decimal? Credit { get; set; }
}
