// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class TempTrialBalanceByTotal
{
    public decimal Account_Sn { get; set; }
    public decimal? Account_No { get; set; }
    public string Account_Name { get; set; }
    public decimal? Debit { get; set; }
    public decimal? Credit { get; set; }
    public decimal? Priv_Credit { get; set; }
    public decimal? Priv_Debit { get; set; }
    public decimal? SumValues { get; set; }
    public decimal? TotalDebitBalance { get; set; }
    public decimal? TotalCreditBalance { get; set; }
    public decimal? DebitBalance { get; set; }
    public decimal? CreditBalance { get; set; }
    public int? BranchID { get; set; }
    public int? UserID { get; set; }
}
