// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class TempTranMaterDetails
{
    public decimal TranSn { get; set; }
    public decimal? Account_Sn { get; set; }
    public decimal? Account_No { get; set; }
    public short? TranTypeID { get; set; }
    public decimal? TranCode { get; set; }
    public DateTime? TranDate { get; set; }
    public string TranTypeDesc { get; set; }
    public string Note { get; set; }
    public decimal? ReferenceCode { get; set; }
    public string TranDesc { get; set; }
    public decimal? Debit { get; set; }
    public decimal? Credit { get; set; }
    public decimal? Priv_Debit { get; set; }
    public decimal? Priv_Credit { get; set; }
    public decimal? SumValues { get; set; }
    public decimal? Balance { get; set; }
    public string Account_Name { get; set; }
    public short? AccounIindex { get; set; }
    public string ReceivedFrom { get; set; }
    public decimal IDCount { get; set; }
    public decimal? CostCentersNo { get; set; }
    public string CostCentersName { get; set; }
    public decimal? running_total { get; set; }
    public string DocCode { get; set; }
    public Guid? LedgerID { get; set; }
    public int? BranchID { get; set; }
    public int? UserID { get; set; }
}
