// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class TempAccounts
{
    public decimal sn { get; set; }
    public decimal? Account_No { get; set; }
    public short? Suspended { get; set; }
    public short? Account_Level { get; set; }
    public short? Final_Account { get; set; }
    public short? Account_Type { get; set; }
    public short? Account_Nature { get; set; }
    public decimal? Main_Account_No { get; set; }
    public string Account_Name { get; set; }
    public string E_Account_Name { get; set; }
    public decimal? Priv_Debit { get; set; }
    public decimal? Priv_Credit { get; set; }
    public string AddressA { get; set; }
    public string AddressB { get; set; }
    public string PhoneA { get; set; }
    public string PhoneB { get; set; }
    public string FaxA { get; set; }
    public string FaxB { get; set; }
    public string Note { get; set; }
    public int? CreatedByUser { get; set; }
    public int? UpdatedByUser { get; set; }
    public DateTime? CreatedDate { get; set; }
}
