// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Tran_TranTempDetails
{
    public int Sn { get; set; }
    public int? TranSn { get; set; }
    public int? Account_Sn { get; set; }
    public int? AccounIindex { get; set; }
    public string TranDesc { get; set; }
    public decimal? Debit { get; set; }
    public decimal? Credit { get; set; }
    public int? CostCentersID { get; set; }
    public int? BranchID { get; set; }
    public int? ProjectId { get; set; }
    public int? YearId { get; set; }
}
