// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Tran_Tran
{
    public int ID { get; set; }
    public int? ReferenceCode { get; set; }
    public int? TranTypeID { get; set; }
    public string DocCode { get; set; }
    public DateTime? TranDate { get; set; }
    public string Note { get; set; }
    public int? BranchID { get; set; }
    public int? UserID_Add { get; set; }
    public int? UserBranch_Add { get; set; }
    public string UserMacAddress_Add { get; set; }
    public DateTime? UserDate_Add { get; set; }
    public int? UserID_Update { get; set; }
    public int? UserBranch_Update { get; set; }
    public string UserMacAddress_Update { get; set; }
    public DateTime? UserDate_Update { get; set; }
    public Guid? LedgerID { get; set; }
    public string ReceivedFrom { get; set; }
    public decimal? TranCode { get; set; }
    public int? ProjectId { get; set; }
    public int? YearId { get; set; }
}
