// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class User_Login
{
    public int ID { get; set; }
    public string Name { get; set; }
    public string PassWord { get; set; }
    public int? BranchID { get; set; }
    public int? GroupID { get; set; }
    public bool? IsActive { get; set; }
    public int? UserID_Add { get; set; }
    public int? UserBranch_Add { get; set; }
    public string UserMacAddress_Add { get; set; }
    public DateTime? UserDate_Add { get; set; }
    public int? UserID_Update { get; set; }
    public int? UserBranch_Update { get; set; }
    public string UserMacAddress_Update { get; set; }
    public DateTime? UserDate_Update { get; set; }
    public string Phone { get; set; }
    public bool? IsOpenDay { get; set; }
    public decimal? MoneyOpenDay { get; set; }
    public string Note { get; set; }
    public DateTime? DateOpen { get; set; }
    public DateTime? DateClose { get; set; }
    public string Crs { get; set; }
    public string PrivateKey { get; set; }
    public string PublicKey { get; set; }
    public string SecretKey { get; set; }
    public string InvoiceHash { get; set; }
    public string ModeInvoice { get; set; }
    public bool? SentXmlZakateNow { get; set; }
}
