// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class User_Screens
{
    public int ID { get; set; }
    public string Screen_Name { get; set; }
    public int? ScreenTypeID { get; set; }
    public int? ScreenNum { get; set; }
    public string ScreenTypeName { get; set; }
    public bool? ISShow { get; set; }
}
