// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class User_Groups
{
    public int ID { get; set; }
    public string Name { get; set; }
    public int? BranchID { get; set; }
    public bool? SellPrice2 { get; set; }
    public bool? SellPrice3 { get; set; }
    public bool? LastPrice { get; set; }
    public bool? AvergPrice { get; set; }
    public bool? ProvePrice { get; set; }
    public int? SelectSellPrice { get; set; }
    public bool? SelectQuantityPrice { get; set; }
    public int? UserID_Add { get; set; }
    public int? UserBranch_Add { get; set; }
    public string UserMacAddress_Add { get; set; }
    public DateTime? UserDate_Add { get; set; }
    public int? UserID_Update { get; set; }
    public int? UserBranch_Update { get; set; }
    public string UserMacAddress_Update { get; set; }
    public DateTime? UserDate_Update { get; set; }
}
