// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Virg_Virgins
{
    public int ID { get; set; }
    public string Name { get; set; }
    public decimal? Price { get; set; }
    public int? GroupShow { get; set; }
}
