// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Virg_Branch
{
    public int ID { get; set; }
    public string Name { get; set; }
    public string Code { get; set; }
    public string Password { get; set; }
    public string Branch { get; set; }
    public bool? ISActive { get; set; }
    public bool? AdminPermission { get; set; }
    public string VirgLogin { get; set; }
    public int? CompID { get; set; }
    public int? TypeID { get; set; }
    public bool? ShowVirg { get; set; }
    public int? FranchiseID { get; set; }
    public bool? ShowAllCustomer { get; set; }
}
