// <auto-generated />
// Source: GTSdb2026 forensic schema export
namespace AlSaqarAccounting.Models;

public sealed class Virg_Master
{
    public int ID { get; set; }
    public int? CustID { get; set; }
}
